version: "3"

services:
  webservice:
    build:
      context: .
      dockerfile: image.Dockerfile
    command:
      ["echo 'Starting in 15s' && sleep 15 && exec java -jar msbanksvc-fat.jar"]
    ports:
      - 80:8888
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
